# Copyright (c) OpenMMLab. All rights reserved.
"""Build a conservative noise-cleaned label directory.

The script consumes confidence-valued masks generated by
``tools/analyze_label_noise.py``.  By default only boundary candidates are
changed to raw label ID 0 (ignore).  Original labels are never modified.

To keep one MMSegmentation dataset prefix for real and pseudo samples, the
output directory contains every unique sample in ``train_pseudo.txt``:

* real samples from ``train.txt`` are conservatively cleaned;
* pseudo samples are hard-linked (or copied if linking is unavailable);
* the output split preserves the original order and repeated pseudo samples.
"""

import argparse
import json
import os
import shutil
from pathlib import Path

import numpy as np
from PIL import Image


NUM_CLASSES = 8


def parse_args():
    parser = argparse.ArgumentParser(
        description='根据噪声分析候选掩码生成保守清洗标签')
    parser.add_argument('--data-root', default='data/mydata')
    parser.add_argument('--real-list', default='train.txt')
    parser.add_argument('--combined-list', default='train_pseudo.txt')
    parser.add_argument('--source-seg-dir', default='SegmentationClass')
    parser.add_argument(
        '--analysis-dir', default='outputs/noise_analysis_v1')
    parser.add_argument(
        '--output-seg-dir', default='SegmentationClassNoiseClean')
    parser.add_argument(
        '--output-list', default='train_pseudo_noiseclean.txt')
    parser.add_argument('--seg-suffix', default='.png')
    parser.add_argument(
        '--max-image-ignore-fraction', type=float, default=0.05,
        help='每张真实标签最多新增Ignore占有效像素比例')
    parser.add_argument(
        '--max-class-ignore-fraction', type=float, default=0.05,
        help='每张图每个类别最多新增Ignore占该类像素比例')
    parser.add_argument(
        '--include-interior', action='store_true',
        help='同时清洗内部候选；第一轮实验不建议开启')
    parser.add_argument(
        '--copy-unchanged', action='store_true',
        help='复制未修改标签；默认优先创建硬链接以节省磁盘')
    parser.add_argument(
        '--overwrite', action='store_true',
        help='允许覆盖输出目录中的同名文件，但不会删除目录其他内容')
    return parser.parse_args()


def validate_args(args):
    for name, value in (
            ('--max-image-ignore-fraction', args.max_image_ignore_fraction),
            ('--max-class-ignore-fraction', args.max_class_ignore_fraction)):
        if not 0.0 <= value <= 1.0:
            raise ValueError(f'{name}必须在[0, 1]范围内')


def read_list(path: Path, allow_duplicates: bool):
    if not path.is_file():
        raise FileNotFoundError(f'列表不存在: {path}')
    lines = []
    for line in path.read_text(encoding='utf-8').splitlines():
        stripped = line.strip()
        if stripped:
            lines.append(stripped.split()[0])
    if not lines:
        raise ValueError(f'列表为空: {path}')
    if not allow_duplicates and len(lines) != len(set(lines)):
        raise ValueError(f'真实标签列表不能包含重复样本: {path}')
    return lines


def sample_relative(name: str, suffix: str):
    relative = Path(name)
    if relative.suffix:
        return relative.with_suffix(suffix)
    return relative.with_suffix(suffix)


def load_gray(path: Path):
    if not path.is_file():
        raise FileNotFoundError(f'文件不存在: {path}')
    with Image.open(path) as image:
        array = np.asarray(image)
    if array.ndim != 2:
        raise ValueError(f'必须是单通道标签或掩码，实际为{array.shape}: {path}')
    return array.astype(np.uint8, copy=False)


def validate_raw_label(label: np.ndarray, path: Path):
    values = np.unique(label)
    allowed = (values == 0) | (values == 255) | (
        (values >= 1) & (values <= NUM_CLASSES))
    if not np.all(allowed):
        raise ValueError(
            f'源标签只能包含0、1-8或255，实际为{values.tolist()}: {path}')


def select_top_indices(indices: np.ndarray, scores_flat: np.ndarray,
                       limit: int):
    if limit <= 0 or indices.size == 0:
        return np.empty(0, dtype=np.int64)
    if indices.size <= limit:
        return indices
    values = scores_flat[indices]
    # Primary key: descending confidence. Secondary key: flat pixel index.
    order = np.lexsort((indices, -values.astype(np.int16)))
    return indices[order[:limit]]


def capped_selection(raw_label: np.ndarray, scores: np.ndarray,
                     max_image_fraction: float, max_class_fraction: float):
    valid = (raw_label >= 1) & (raw_label <= NUM_CLASSES)
    candidate = valid & (scores > 0)
    selected_flat_parts = []
    raw_flat = raw_label.reshape(-1)
    scores_flat = scores.reshape(-1)

    per_class_candidates = np.zeros(NUM_CLASSES, dtype=np.int64)
    per_class_selected = np.zeros(NUM_CLASSES, dtype=np.int64)
    per_class_pixels = np.zeros(NUM_CLASSES, dtype=np.int64)
    for raw_id in range(1, NUM_CLASSES + 1):
        class_mask = raw_flat == raw_id
        class_pixels = int(class_mask.sum())
        indices = np.flatnonzero(class_mask & candidate.reshape(-1))
        per_class_pixels[raw_id - 1] = class_pixels
        per_class_candidates[raw_id - 1] = indices.size
        class_limit = int(np.floor(class_pixels * max_class_fraction))
        chosen = select_top_indices(indices, scores_flat, class_limit)
        per_class_selected[raw_id - 1] = chosen.size
        if chosen.size:
            selected_flat_parts.append(chosen)

    if selected_flat_parts:
        selected_indices = np.concatenate(selected_flat_parts)
    else:
        selected_indices = np.empty(0, dtype=np.int64)

    image_limit = int(np.floor(int(valid.sum()) * max_image_fraction))
    selected_indices = select_top_indices(
        selected_indices, scores_flat, image_limit)
    selected = np.zeros(raw_label.size, dtype=bool)
    selected[selected_indices] = True
    selected = selected.reshape(raw_label.shape)

    # Recompute final per-class counts after applying the global image cap.
    per_class_final = np.zeros(NUM_CLASSES, dtype=np.int64)
    for raw_id in range(1, NUM_CLASSES + 1):
        per_class_final[raw_id - 1] = int(
            np.count_nonzero(selected & (raw_label == raw_id)))
    return selected, dict(
        valid_pixels=int(valid.sum()),
        candidate_pixels=int(candidate.sum()),
        selected_pixels=int(selected.sum()),
        class_pixels=per_class_pixels.tolist(),
        class_candidates=per_class_candidates.tolist(),
        class_selected=per_class_final.tolist())


def install_unchanged(source: Path, destination: Path, copy_only: bool,
                      overwrite: bool):
    destination.parent.mkdir(parents=True, exist_ok=True)
    if destination.exists():
        if not overwrite:
            raise FileExistsError(f'输出文件已经存在: {destination}')
        destination.unlink()
    if not copy_only:
        try:
            os.link(str(source), str(destination))
            return 'hardlink'
        except OSError:
            pass
    shutil.copy2(str(source), str(destination))
    return 'copy'


def count_install_method(totals, method: str):
    if method == 'hardlink':
        totals['hardlinks'] += 1
    elif method == 'copy':
        totals['copies'] += 1
    else:
        raise RuntimeError(f'未知安装方式: {method}')


def save_cleaned(label: np.ndarray, destination: Path, overwrite: bool):
    destination.parent.mkdir(parents=True, exist_ok=True)
    if destination.exists() and not overwrite:
        raise FileExistsError(f'输出文件已经存在: {destination}')
    Image.fromarray(label.astype(np.uint8), mode='L').save(
        destination, format='PNG')


def main():
    args = parse_args()
    validate_args(args)

    data_root = Path(args.data_root)
    real_names = read_list(data_root / args.real_list, allow_duplicates=False)
    combined_names = read_list(
        data_root / args.combined_list, allow_duplicates=True)
    real_set = set(real_names)
    combined_set = set(combined_names)
    missing_real = sorted(real_set - combined_set)
    if missing_real:
        raise ValueError(
            f'联合列表缺少{len(missing_real)}个真实样本，例如{missing_real[:5]}')

    source_dir = data_root / args.source_seg_dir
    output_dir = data_root / args.output_seg_dir
    analysis_dir = Path(args.analysis_dir)
    boundary_dir = analysis_dir / 'boundary_candidates'
    interior_dir = analysis_dir / 'interior_candidates'
    summary_path = analysis_dir / 'summary.json'
    if not summary_path.is_file():
        raise FileNotFoundError(
            f'缺少噪声分析汇总: {summary_path}。请先完整运行'
            'tools/analyze_label_noise.py。')
    if output_dir.exists() and any(output_dir.iterdir()) and not args.overwrite:
        raise FileExistsError(
            f'输出标签目录非空: {output_dir}。为保护已有结果，请换目录；'
            '确认需要覆盖同名文件时增加--overwrite。')
    output_dir.mkdir(parents=True, exist_ok=True)

    output_list = Path(args.output_list)
    if not output_list.is_absolute():
        output_list = data_root / output_list
    if output_list.exists() and not args.overwrite:
        raise FileExistsError(f'输出训练列表已经存在: {output_list}')

    unique_names = list(dict.fromkeys(combined_names))
    totals = dict(
        unique_samples=len(unique_names),
        real_samples=len(real_set),
        pseudo_samples=len(combined_set - real_set),
        modified_real_samples=0,
        valid_real_pixels=0,
        candidate_pixels=0,
        ignored_added=0,
        hardlinks=0,
        copies=0,
        class_pixels=np.zeros(NUM_CLASSES, dtype=np.int64),
        class_candidates=np.zeros(NUM_CLASSES, dtype=np.int64),
        class_ignored=np.zeros(NUM_CLASSES, dtype=np.int64))
    per_image = []

    print(
        f'联合列表行数={len(combined_names)}，唯一样本={len(unique_names)}，'
        f'真实样本={len(real_set)}，伪样本={len(combined_set - real_set)}')
    print(
        f'清洗范围: 边界候选 + 内部候选={args.include_interior}，'
        f'单图上限={args.max_image_ignore_fraction:.1%}，'
        f'单类上限={args.max_class_ignore_fraction:.1%}')
    print('原始SegmentationClass不会被修改。')

    for index, name in enumerate(unique_names, start=1):
        relative = sample_relative(name, args.seg_suffix)
        source = source_dir / relative
        destination = output_dir / relative
        if not source.is_file():
            raise FileNotFoundError(f'源标签不存在: {source}')

        if name not in real_set:
            method = install_unchanged(
                source, destination, args.copy_unchanged, args.overwrite)
            count_install_method(totals, method)
        else:
            raw_label = load_gray(source)
            validate_raw_label(raw_label, source)
            boundary_path = boundary_dir / relative
            boundary_scores = load_gray(boundary_path)
            if boundary_scores.shape != raw_label.shape:
                raise ValueError(
                    f'边界候选与标签尺寸不一致: {boundary_path}, {source}')
            scores = boundary_scores.copy()
            if args.include_interior:
                interior_path = interior_dir / relative
                interior_scores = load_gray(interior_path)
                if interior_scores.shape != raw_label.shape:
                    raise ValueError(
                        f'内部候选与标签尺寸不一致: {interior_path}, {source}')
                scores = np.maximum(scores, interior_scores)

            selected, stats = capped_selection(
                raw_label, scores, args.max_image_ignore_fraction,
                args.max_class_ignore_fraction)
            totals['valid_real_pixels'] += stats['valid_pixels']
            totals['candidate_pixels'] += stats['candidate_pixels']
            totals['ignored_added'] += stats['selected_pixels']
            totals['class_pixels'] += np.asarray(
                stats['class_pixels'], dtype=np.int64)
            totals['class_candidates'] += np.asarray(
                stats['class_candidates'], dtype=np.int64)
            totals['class_ignored'] += np.asarray(
                stats['class_selected'], dtype=np.int64)

            if stats['selected_pixels']:
                clean_label = raw_label.copy()
                # Raw ID 0 becomes train ignore 255 after reduce_zero_label.
                clean_label[selected] = 0
                save_cleaned(clean_label, destination, args.overwrite)
                totals['modified_real_samples'] += 1
            else:
                method = install_unchanged(
                    source, destination, args.copy_unchanged, args.overwrite)
                count_install_method(totals, method)

            per_image.append(dict(name=name, **stats))

        if index % 100 == 0 or index == len(unique_names):
            print(
                f'已安装 {index}/{len(unique_names)}，累计新增Ignore='
                f'{totals["ignored_added"]}')

    output_list.parent.mkdir(parents=True, exist_ok=True)
    output_list.write_text(
        '\n'.join(combined_names) + '\n', encoding='utf-8')

    report = dict(
        source=dict(
            real_list=str(data_root / args.real_list),
            combined_list=str(data_root / args.combined_list),
            source_seg_dir=str(source_dir),
            analysis_summary=str(summary_path)),
        output=dict(
            seg_dir=str(output_dir),
            train_list=str(output_list)),
        policy=dict(
            include_interior=args.include_interior,
            max_image_ignore_fraction=args.max_image_ignore_fraction,
            max_class_ignore_fraction=args.max_class_ignore_fraction),
        totals=dict(
            unique_samples=totals['unique_samples'],
            real_samples=totals['real_samples'],
            pseudo_samples=totals['pseudo_samples'],
            modified_real_samples=totals['modified_real_samples'],
            valid_real_pixels=totals['valid_real_pixels'],
            candidate_pixels=totals['candidate_pixels'],
            ignored_added=totals['ignored_added'],
            ignored_added_rate=(
                totals['ignored_added'] / totals['valid_real_pixels']
                if totals['valid_real_pixels'] else 0.0),
            hardlinks=totals['hardlinks'],
            copies=totals['copies'],
            class_pixels=totals['class_pixels'].tolist(),
            class_candidates=totals['class_candidates'].tolist(),
            class_ignored=totals['class_ignored'].tolist()),
        images=per_image)
    report_path = output_dir / 'noise_clean_build.json'
    report_path.write_text(
        json.dumps(report, ensure_ascii=False, indent=2), encoding='utf-8')

    print('\n清洗标签安装完成')
    print(f'  修改的真实标签: {totals["modified_real_samples"]}')
    print(
        '  新增Ignore比例: '
        f'{report["totals"]["ignored_added_rate"]:.3%}')
    print(f'  硬链接: {totals["hardlinks"]}，复制: {totals["copies"]}')
    print(f'  标签目录: {output_dir}')
    print(f'  训练列表: {output_list}')
    print(f'  构建报告: {report_path}')


if __name__ == '__main__':
    main()